#!/usr/bin/env node
/**
 * Records docs/demo.gif: the CLI running against Apple's last two 10-Ks.
 *
 * The page this drives is generated by scripts/make-demo-page.py from the real
 * output of the real command, so the GIF cannot show something the tool does
 * not actually print. If the tool breaks, the GIF cannot be recorded.
 *
 * Playwright screenshots each frame and gifenc encodes them, because the ffmpeg
 * Playwright bundles is a webm-only build with no GIF muxer.
 *
 *   python scripts/make-demo-page.py
 *   node scripts/record-gif.mjs
 */

import { mkdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { chromium } from '@playwright/test';
import gifenc from 'gifenc';
import pngjs from 'pngjs';

const { GIFEncoder, applyPalette, quantize } = gifenc;
const { PNG } = pngjs;

const PAGE = resolve('build/terminal.html');
const OUT = 'docs/demo.gif';
const WIDTH = 900;
const HEIGHT = 600;

// Two lines of output per frame. One per frame reads more naturally and
// produces a 12MB GIF, which nobody waits for on a README.
const LINES_PER_FRAME = 2;

const browser = await chromium.launch();
const page = await browser.newPage({
  viewport: { width: WIDTH, height: HEIGHT },
  deviceScaleFactor: 1,
});
await page.goto(pathToFileURL(PAGE).href, { waitUntil: 'load' });

const { typingEnd, total } = await page.evaluate(() => ({
  typingEnd: window.__typingEnd,
  total: window.__total,
}));

const frames = [];

async function shoot(delay) {
  const png = PNG.sync.read(await page.screenshot({ type: 'png' }));
  frames.push({ data: new Uint8Array(png.data), delay });
}

for (let step = 0; step <= total; step += step < typingEnd ? 1 : LINES_PER_FRAME) {
  await page.evaluate((s) => window.__frame(s), step);
  // Slower while typing, quicker through the output, so the eye reads the
  // command first and then follows the results down the screen.
  await shoot(step < typingEnd ? 60 : 130);
}

await page.evaluate((s) => window.__frame(s), total);
await shoot(2800); // hold on the finished screen before it loops

await browser.close();

const encoder = GIFEncoder();
for (const frame of frames) {
  const palette = quantize(frame.data, 256, { format: 'rgb444' });
  const index = applyPalette(frame.data, palette, 'rgb444');
  encoder.writeFrame(index, WIDTH, HEIGHT, { palette, delay: frame.delay });
}
encoder.finish();

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, encoder.bytes());

const mb = (statSync(OUT).size / 1048576).toFixed(1);
console.log(`  wrote ${OUT}  ${frames.length} frames  ${mb} MB`);
