"""Filing HTML -> a list of clean text blocks.

EDGAR HTML is machine-generated by a dozen different filing agents and looks it.
A paragraph might be a ``<p>``, or a ``<div>``, or a one-cell ``<table>`` used
for indentation, or forty ``<span>`` elements each carrying one word and its own
inline font. Modern filings are inline XBRL, which layers thousands of invisible
``<ix:*>`` tags over the top and hides a whole header block off-screen.

The job here is to get back to something a diff can work with: the visible
paragraphs, in order, with the whitespace normalised and the invisible parts
gone.
"""

from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass

import lxml.html
from lxml import etree

#: Tags whose boundaries end a paragraph. Everything else is inline.
BLOCK_TAGS = frozenset([
    "address", "article", "aside", "blockquote", "br", "caption", "center", "div", "dd", "dl",
    "dt", "fieldset", "figcaption", "figure", "footer", "form", "h1", "h2", "h3", "h4", "h5",
    "h6", "header", "hr", "li", "main", "nav", "ol", "p", "pre", "section", "table", "tbody",
    "td", "tfoot", "th", "thead", "tr", "ul"
])

#: Tags that never contribute visible text.
DROP_TAGS = frozenset([
    "script", "style", "noscript", "head", "meta", "link", "title", "ix:header", "ix:hidden",
    "ix:references"
])

_HIDDEN = re.compile(r"display\s*:\s*none|visibility\s*:\s*hidden", re.I)
_WS = re.compile(r"[ \t\u00a0\u2007\u202f]+")
_NEWLINES = re.compile(r"\n{2,}")
#: Page furniture: bare page numbers, "Table of Contents" links, form headers
#: that repeat on every page of a paper-formatted filing.
_FURNITURE = re.compile(
    r"^(?:table\s+of\s+contents|index|page\s*\|?\s*\d+|-?\s*\d{1,4}\s*-?|"
    r"form\s+10-[kq](?:\s*/\s*a)?|\d{1,3}\s*\|\s*\d{4}\s+form\s+10-[kq])$",
    re.I,
)


@dataclass(frozen=True)
class Block:
    """One visible paragraph of a filing."""

    text: str
    kind: str = "text"  # "text" | "table" | "heading"

    def __len__(self) -> int:
        return len(self.text)


def _visible(el: etree._Element) -> bool:
    style = el.get("style") or ""
    if _HIDDEN.search(style):
        return False
    # Inline XBRL hides its non-displayed facts inside a zero-size div rather
    # than with display:none, which is why checking the style alone is not enough.
    return el.get("aria-hidden") != "true"


def _normalise(text: str) -> str:
    """Collapse whitespace and fold the typographic characters filings love."""
    # NFKC turns non-breaking spaces, ligatures and full-width punctuation into
    # their plain equivalents, so an em dash swapped for an en dash between two
    # filings does not register as a change.
    text = unicodedata.normalize("NFKC", text)
    text = text.replace("\u2018", "'").replace("\u2019", "'")
    text = text.replace("\u201c", '"').replace("\u201d", '"')
    text = text.replace("\u2013", "-").replace("\u2014", "--")
    text = _WS.sub(" ", text)
    return text.strip()


def _walk(el: etree._Element, out: list[str]) -> None:
    tag = el.tag if isinstance(el.tag, str) else ""
    tag = tag.split("}")[-1].lower() if "}" in tag else tag.lower()

    if tag in DROP_TAGS or (tag.startswith("ix:") and tag in DROP_TAGS):
        return
    if isinstance(el, etree._Comment | etree._ProcessingInstruction):
        return
    if not _visible(el):
        return

    block = tag in BLOCK_TAGS
    if block:
        out.append("\n")
    if el.text:
        out.append(el.text)
    for child in el:
        _walk(child, out)
        if child.tail:
            out.append(child.tail)
    if block:
        out.append("\n")


def to_text(html: str | bytes) -> str:
    """Filing HTML -> plain text with paragraph breaks preserved."""
    if isinstance(html, str):
        html = html.encode("utf-8", errors="replace")
    if not html.strip():
        return ""
    # recover=True matters: a meaningful share of filings have unclosed tags that
    # a strict parser refuses outright.
    parser = lxml.html.HTMLParser(recover=True, encoding="utf-8")
    try:
        root = lxml.html.document_fromstring(html, parser=parser)
    except (etree.ParserError, ValueError):
        return ""

    for el in root.iter():
        tag = el.tag if isinstance(el.tag, str) else ""
        if tag.split("}")[-1].lower() in DROP_TAGS:
            parent = el.getparent()
            if parent is not None:
                parent.remove(el)

    chunks: list[str] = []
    body = root.find("body")
    _walk(body if body is not None else root, chunks)

    lines = ("".join(chunks)).split("\n")
    kept = [_normalise(line) for line in lines]
    return _NEWLINES.sub("\n\n", "\n".join(x for x in kept if x))


def _is_heading(text: str) -> bool:
    """Short, title-ish lines that anchor a section rather than say anything."""
    if len(text) > 120 or text.endswith((".", ";", ",")):
        return False
    words = text.split()
    if not 1 <= len(words) <= 16:
        return False
    letters = [c for c in text if c.isalpha()]
    if not letters:
        return False
    upper = sum(c.isupper() for c in letters) / len(letters)
    return upper > 0.6 or bool(re.match(r"^item\s+\d", text, re.I))


def to_blocks(html: str | bytes, *, min_chars: int = 40) -> list[Block]:
    """Filing HTML -> the blocks worth diffing.

    Blocks shorter than ``min_chars`` survive only if they look like headings;
    everything else that short is page furniture, a stray table cell, or a
    footnote marker, and keeping it buries the real changes in noise.
    """
    blocks: list[Block] = []
    for raw in to_text(html).split("\n"):
        text = raw.strip()
        if not text or _FURNITURE.match(text):
            continue
        if _is_heading(text):
            blocks.append(Block(text, "heading"))
        elif len(text) >= min_chars:
            # A line that is mostly digits and separators is a table row that
            # lost its markup on the way through. Tag it so the scorer can stop
            # a reformatted numbers table reading as a rewritten risk factor.
            digits = sum(c.isdigit() for c in text)
            blocks.append(Block(text, "table" if digits / len(text) > 0.30 else "text"))
    return blocks
